name: collect


on:
  schedule:
    - cron: "30 8 * * *"

jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run 
      run: |
        python main.py

